### ISSUE TITLE
Card showing blank

### ISSUE THREAD

**Issue by zevulos** [klejejs/lovelace-keep-notes-card#1]
The card is showing blank on my dashboard, i have the sensor working correctly.
Ive added card-tools.js and keep-notes-card.js to my /config/www/ folder and added the following resources: /local/card-tools..js     &     /local/keep-notes-cards.js

I've tried a different browser and clearing cache as well/

**Comment by klejejs** [comment]
I am sorry to inform you, but this repository is being archived due to other similar Home Assistant integrations being maintained. Please feel free to check those out.
